# Generated by Django 4.0.4 on 2022-04-20 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographicReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('app_title', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotographicItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=250)),
                ('pictureOne', models.CharField(max_length=100)),
                ('pictureTwo', models.CharField(max_length=100)),
                ('fk_informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardenas.photographicreport')),
            ],
        ),
    ]
