# Generated by Django 4.0.4 on 2022-04-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardenas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographicitem',
            name='pictureOne',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='photographicitem',
            name='pictureTwo',
            field=models.CharField(max_length=150),
        ),
    ]
