# Generated by Django 4.0.4 on 2022-05-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('maintenance_worker', models.CharField(max_length=100)),
                ('maintenance_engineer', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('fire_network', models.CharField(max_length=100)),
                ('contractor', models.CharField(max_length=100)),
                ('contratista', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
